---
- name: 1. K3s 설치 스크립트 다운로드 및 실행
  shell: curl -sfL https://get.k3s.io | sh -
  args:
    creates: /usr/local/bin/k3s # 파일이 있으면 설치된 걸로 간주하고 건너뜀
    
- name: 2. 토큰 읽기
  slurp:
    src: /var/lib/rancher/k3s/server/node-token
  register: k3s_token_base64

- name: 3. 토큰 값 디코딩하여 변수에 저장
  set_fact:
    # slurp로 읽으면 인코딩됨. 따라서 사람이 읽을 수 있게 풀어야 함
    k3s_token: "{{ k3s_token_base64.content | b64decode | trim }}"
