---
# 1. 기초 공사
- name: swap 설정 및 docker 정리
  hosts: k3s_cluster
  become: yes
  roles:
    - common

# 2. Docker 설치 및 테스트
# - name: Docker 자가 치유 테스트
#  hosts: all
#  become: yes
#  roles:
#    - docker
#   K3s 도입하면서 실직하심

# 3. master 노드 구축
# K3s 서버 설치하고 토큰 생성
- name: K3s master 셋업
  hosts: master
  become: yes
  roles:
    - k3s_master

# 4. worker 노드 구축
# master의 ip와 토큰을 받아와서 연결
- name: K3s worker 셋업
  hosts: worker
  become: yes
  roles:
    - k3s_worker
